services:
  laboutik_postgres:
    image: postgres:11.5-alpine
    restart: always
    env_file: .env
    container_name: laboutik_postgres
    hostname: laboutik_postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - laboutik_backend

  laboutik_memcached:
    image: memcached:1.6
    container_name: laboutik_memcached
    hostname: laboutik_memcached
    restart: always
    networks:
      - laboutik_backend

  laboutik_redis:
    image: redis:6-alpine
    restart: always
    env_file: .env
    container_name: laboutik_redis
    hostname: laboutik_redis
    networks:
      - laboutik_backend

  laboutik_django:
    image: tibillet/laboutik:latest
    restart: always
    env_file: .env
    container_name: laboutik_django
    hostname: laboutik_django
    volumes:
      - ./www:/DjangoFiles/www
      - ./logs:/DjangoFiles/logs
      - ./backup:/Backup
      - ./ssh:/home/tibillet/.ssh # if you want to use borgbackup with ssh
    links:
      - laboutik_postgres:postgres
      - laboutik_redis:redis
      - laboutik_memcached:memcached
    depends_on:
      - laboutik_postgres
      - laboutik_redis
      - laboutik_memcached
    networks:
      - laboutik_backend
    # only useful for dev purpose :
    # extra_hosts:
    #   - "fedow.tibillet.localhost:172.17.0.1"
    #   - "lespass.tibillet.localhost:172.17.0.1"
    #   - "cashless.tibillet.localhost:172.17.0.1"


  laboutik_nginx:
    image: nginx
    restart: always
    container_name: laboutik_nginx
    hostname: laboutik_nginx
    depends_on:
      - laboutik_django
    links:
      - laboutik_django:laboutik_django
    volumes:
      - ./www:/DjangoFiles/www
      - ./logs:/DjangoFiles/logs
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.laboutik_nginx.tls.certresolver=myresolver
      - traefik.http.routers.laboutik_nginx.rule=Host(`${DOMAIN}`)
    networks:
      - frontend
      - laboutik_backend

networks:
  frontend:
    external: true
  laboutik_backend: